### ISSUE TITLE
Errors when importing in React Native

### ISSUE THREAD

**Issue by Vid201** [iotaledger-archive/mam.client.js#30]
Following steps provided here https://www.npmjs.com/package/@iota/mam when importing library to React Native, but problem after problem appears. Is it possible to provide more detailed step by step instructions about how to import the library?

First problem that appears is **undefined is not an object (evaluating 'RNRandomBytes.seed')**. I did rn-nodeify and everything that is advised in the link above.

**Comment by Vid201** [comment]
I would really appreciate if someone (who knows how this is done) could upload empty project with everything set up. Beacause even if I fix this problem, another 10 appears.

**Comment by rajivshah3** [comment]
@Vid201 could you provide some sample code? I haven't used `mam.client.js` but I might be able to help with the errors from React Native

**Comment by Vid201** [comment]
@rajivshah3 There is no special sample code. I created new empty React Native project, run npm i --save @iota/mam and did rn-nodeify. I added import * as Mam from 'mam.client.js' in my main .js script and the app doesn't load properly. I received different errors and found different solutions but in the end I get error I can't fix.

I actually don't have troubles with the library but with setting up the project. That's why I think it would be nice if someone could upload empty project with everything set up. Then we can just clone that project and start development.

**Comment by rajivshah3** [comment]
@Vid201 ok, finally got it to work 😅 for some reason it involved more work than I expected. The example project is at https://github.com/rajivshah3/react-native-mam-example

**Comment by Vid201** [comment]
@rajivshah3 I knew there is someone who can do it. Thank you! 🥇

**Comment by sobolev-alexey** [comment]
@Vid201 is the issue solved now? Can we close this ticket?

**Comment by Vid201** [comment]
@sobolev-alexey It is not solved: https://github.com/rajivshah3/react-native-mam-example/issues/1 . But I think this issue is related to React Native, not to mam.client.js.

**Comment by obany** [comment]
We will close this for now as the issue appears to be with React Native and not specifically this package. If there is an issue which is caused by the lib itself we can always reopen.
